version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  app:
    depends_on:
      - mongo
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=microservice_db
      - DB_PORT=8081
    stdin_open: true
    tty: true
volumes:
  db:
